/**
 * SafeLand Fork Generator
 *
 * Main generator orchestrator:
 * 1. Validates country config against JSON schema
 * 2. Generates .env files with injected parameters
 * 3. Copies contract templates and injects parameters
 * 4. Generates deployment documentation
 * 5. Outputs complete fork ready for deployment
 *
 * Usage:
 *   node generator.js --config countries/senegal.json --output ../safeland-senegal
 *
 * Phase 1 MVP (Apr-May 2026):
 * - JSON schema validation only
 * - .env file generation with parameter injection
 * - Basic template copy (no Solidity templating yet)
 * - Documentation generation
 *
 * Phase 2+ enhancements:
 * - Solidity contract parameter injection
 * - Interactive CLI wizard
 * - Subgraph generation
 * - CI/CD integration
 */

const fs = require('fs');
const path = require('path');
const Ajv = require('ajv'); // npm install ajv

/**
 * Load and validate JSON schema
 * @returns {object} Parsed schema
 */
function loadSchema() {
  const schemaPath = path.join(__dirname, 'schema.json');
  const schemaContent = fs.readFileSync(schemaPath, 'utf8');
  return JSON.parse(schemaContent);
}

/**
 * Validate country config against schema
 * @param {object} config - Country configuration
 * @param {object} schema - JSON schema
 * @returns {object} { valid: boolean, errors: [] }
 */
function validateConfig(config, schema) {
  const ajv = new Ajv();
  const validate = ajv.compile(schema);
  const valid = validate(config);

  return {
    valid,
    errors: valid ? [] : validate.errors.map(err => ({
      path: err.instancePath || 'root',
      message: err.message,
    })),
  };
}

/**
 * Generate .env.local file with injected parameters
 * @param {object} config - Country configuration
 * @param {string} outputDir - Output directory path
 */
function generateEnvFile(config, outputDir) {
  const envContent = `# SafeLand ${config.name.toUpperCase()} Configuration
# Auto-generated by fork-generator on ${new Date().toISOString()}

# Blockchain Configuration
BLOCKCHAIN_NETWORK=${config.blockchain}
BLOCKCHAIN_ID=${config.blockchainId}
RPC_URL=${config.rpc_url}

# Country-Specific Configuration
COUNTRY_NAME=${config.name}
COUNTRY_LANGUAGE=${config.language}
COUNTRY_CURRENCY=${config.currency}
INHERITANCE_SCHOOL=${config.inheritance_school}

# Fiscal Rules
DGI_PERCENT=${config.fiscal_rules.dgi_percent}
ANCFCC_PERCENT=${config.fiscal_rules.ancfcc_percent}
PLATFORM_FEE_BPS=${config.fiscal_rules.platform_fee_bps}

# Supported Regions (comma-separated)
REGIONS=${config.regions.join(',')}

# Feature Modules
MODULE_ESCROW=${config.modules.escrow}
MODULE_SUCCESSION=${config.modules.succession}
MODULE_MARKETPLACE=${config.modules.marketplace}
MODULE_JUSTICE=${config.modules.justice}
MODULE_TIMELOCK=${config.modules.timelock}

# Contact Information
LAND_REGISTRY="${config.contacts?.land_registry || ''}"
SUPPORT_EMAIL="${config.contacts?.support_email || ''}"
SUPPORT_PHONE="${config.contacts?.support_phone || ''}"
ESCALATION_EMAIL="${config.contacts?.escalation_email || ''}"

# Deployment Configuration (to be set post-generation)
DEPLOYED_NFT_ADDRESS=0x
DEPLOYED_REGISTRY_ADDRESS=0x
DEPLOYED_ESCROW_ADDRESS=0x
DEPLOYED_FRIDDA_ADDRESS=0x
DEPLOYED_JUSTICE_ADDRESS=0x
DEPLOYED_TIMELOCK_ADDRESS=0x

# API Configuration
API_PORT=3001
API_ENV=development
JWT_SECRET=change_me_in_production
JWT_EXPIRY=24h

# Database Configuration
DB_PATH=./data/safeland.db
DB_BACKUP_PATH=./data/backup/

# Logging
LOG_LEVEL=info
LOG_FORMAT=json

# Security
NODE_ENV=development
`;

  const envPath = path.join(outputDir, '.env.local');
  fs.writeFileSync(envPath, envContent, 'utf8');
  console.log(`✓ Generated ${envPath}`);
}

/**
 * Copy and generate deployment guide
 * @param {object} config - Country configuration
 * @param {string} outputDir - Output directory path
 */
function generateDeploymentGuide(config, outputDir) {
  const guide = `# SafeLand ${config.name.toUpperCase()} - Deployment Guide

## Overview

This is a SafeLand fork generated for ${config.name.toUpperCase()} on ${config.blockchain.toUpperCase()} blockchain.

### Key Configuration

- **Blockchain:** ${config.blockchain} (Chain ID: ${config.blockchainId})
- **RPC Endpoint:** ${config.rpc_url}
- **Inheritance School:** ${config.inheritance_school}
- **Fiscal Rules:**
  - DGI Tax: ${config.fiscal_rules.dgi_percent}%
  - Land Registry Fee: ${config.fiscal_rules.ancfcc_percent}%
  - Platform Fee: ${config.fiscal_rules.platform_fee_bps} bps (0.${String(config.fiscal_rules.platform_fee_bps).padStart(2, '0')}%)
- **Supported Regions:** ${config.regions.join(', ')}
- **Enabled Modules:** ${Object.entries(config.modules)
    .filter(([, enabled]) => enabled)
    .map(([name]) => name)
    .join(', ')}

## Pre-Deployment Checklist

- [ ] Install dependencies: \`npm install\`
- [ ] Review \`.env.local\` configuration
- [ ] Verify RPC endpoint connectivity: \`curl ${config.rpc_url}\`
- [ ] Ensure sufficient native token balance (for gas)
- [ ] Review contract ABIs in \`contracts/\`
- [ ] Run tests: \`npm test\`

## Deployment Steps

### 1. Compile Contracts

\`\`\`bash
npm run compile
\`\`\`

### 2. Deploy to ${config.blockchain.toUpperCase()} Testnet

\`\`\`bash
npm run deploy:testnet
\`\`\`

This will:
1. Deploy smart contracts (with UUPS proxy pattern)
2. Initialize contracts with country-specific parameters
3. Save deployed addresses to \`deployed-addresses.json\`
4. Update \`.env.local\` with deployed contract addresses

### 3. Verify Deployment

\`\`\`bash
npm run verify:deployment
\`\`\`

Checks:
- All contracts deployed
- Initialization parameters set correctly
- Event logs recorded on-chain

### 4. Run Backend & Frontend

**Terminal 1 - Backend:**
\`\`\`bash
cd backend
npm install
npm run dev
\`\`\`

**Terminal 2 - Frontend:**
\`\`\`bash
cd frontend
npm install
npm run dev
\`\`\`

Access dashboard at http://localhost:3000

### 5. Data Migration (if applicable)

For legacy title migration from ${config.contacts?.land_registry || 'land registry'}:

\`\`\`bash
npm run migrate:data -- --source legacy.csv --count 1000
\`\`\`

### 6. UAT with ${config.contacts?.land_registry || 'Land Registry'}

- Create 5 test users
- Test property registration workflow
- Test escrow settlement with fees
- Verify succession module (if enabled)
- Sign-off on data accuracy

## Post-Deployment

### Monitoring

- Monitor blockchain events via TheGraph subgraph
- Track error rates and user activity in admin dashboard
- Set up alerts for critical failures

### Support Contacts

- Support Email: ${config.contacts?.support_email || '[not configured]'}
- Support Phone: ${config.contacts?.support_phone || '[not configured]'}
- Escalation: ${config.contacts?.escalation_email || '[not configured]'}

### Production Readiness

Before mainnet deployment:
- Complete security audit (CertiK or equivalent)
- Load testing (>1000 concurrent users)
- Disaster recovery procedures documented
- Backup and recovery tested

## Troubleshooting

### RPC Connection Issues

\`\`\`bash
# Test RPC connectivity
curl -X POST ${config.rpc_url} \\
  -H "Content-Type: application/json" \\
  -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
\`\`\`

### Insufficient Gas

Ensure account has minimum balance:
- Testnet: 0.5 native token
- Mainnet: 5+ native token (for deployment costs)

### Contract Initialization Failures

Check .env.local parameters match schema:
- DGI_PERCENT: 0-10
- ANCFCC_PERCENT: 0-5
- PLATFORM_FEE_BPS: 1-100

## Additional Resources

- Generator Documentation: \`backend/src/generator/README.md\`
- Smart Contract Architecture: \`docs/\`
- Frontend Setup: \`frontend/README.md\`
- Backend API: \`backend/README.md\`

---

Generated: ${new Date().toISOString()}
Generator: SafeLand Fork Generator v0.1
`;

  const guidePath = path.join(outputDir, 'DEPLOYMENT-GUIDE.md');
  fs.writeFileSync(guidePath, guide, 'utf8');
  console.log(`✓ Generated ${guidePath}`);
}

/**
 * Main generator function
 * @param {object} options - Command-line options
 */
async function generate(options) {
  try {
    // Load schema
    console.log('Loading JSON schema...');
    const schema = loadSchema();

    // Load and parse config
    console.log(`Reading config: ${options.config}`);
    if (!fs.existsSync(options.config)) {
      throw new Error(`Config file not found: ${options.config}`);
    }

    const configContent = fs.readFileSync(options.config, 'utf8');
    let config;
    try {
      config = JSON.parse(configContent);
    } catch (err) {
      throw new Error(`Invalid JSON in config: ${err.message}`);
    }

    // Validate config
    console.log('Validating config against schema...');
    const validation = validateConfig(config, schema);
    if (!validation.valid) {
      console.error('Validation failed:');
      validation.errors.forEach(err => {
        console.error(`  ${err.path}: ${err.message}`);
      });
      process.exit(1);
    }
    console.log('✓ Config valid');

    // If --validate-only, stop here
    if (options['validate-only']) {
      console.log('✓ Validation complete (--validate-only flag set)');
      process.exit(0);
    }

    // Create output directory
    const outputDir = options.output || `./generated-${config.name}`;
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
      console.log(`✓ Created output directory: ${outputDir}`);
    }

    // Generate .env file
    console.log('Generating .env.local with injected parameters...');
    generateEnvFile(config, outputDir);

    // Generate deployment guide
    console.log('Generating DEPLOYMENT-GUIDE.md...');
    generateDeploymentGuide(config, outputDir);

    // Phase 2+ will add:
    // - Contract template copy + parameter injection
    // - Subgraph generation
    // - Docker Compose setup

    console.log(`\n✓ Fork generation complete!`);
    console.log(`\nNext steps:`);
    console.log(`  1. Review .env.local: ${path.join(outputDir, '.env.local')}`);
    console.log(`  2. Copy contracts and backend code`);
    console.log(`  3. Deploy: npm run deploy:testnet`);
    console.log(`  4. See DEPLOYMENT-GUIDE.md for full instructions`);

    process.exit(0);
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

// CLI entry point
if (require.main === module) {
  const yargs = require('yargs');
  const argv = yargs
    .option('config', {
      alias: 'c',
      description: 'Path to country configuration JSON file',
      type: 'string',
    })
    .option('output', {
      alias: 'o',
      description: 'Output directory for generated fork',
      type: 'string',
    })
    .option('validate-only', {
      description: 'Validate config without generating',
      type: 'boolean',
      default: false,
    })
    .option('show-schema', {
      description: 'Print JSON schema and exit',
      type: 'boolean',
      default: false,
    })
    .option('list-configs', {
      description: 'List available country configs',
      type: 'boolean',
      default: false,
    })
    .demandOption(['config'], 'Please provide --config with path to country configuration JSON')
    .help()
    .argv;

  if (argv['show-schema']) {
    const schema = loadSchema();
    console.log(JSON.stringify(schema, null, 2));
    process.exit(0);
  }

  generate(argv);
}

module.exports = { generate, validateConfig, loadSchema, generateEnvFile, generateDeploymentGuide };
